---

dimensions:
  Preparation:
    - name: multipleChoice
      questionType: multipleChoice

    - name: triangle
      questionType: triangle

  Order:
  - 1,2
  - 2,1

  Test order:
    - A, B
    - B, A
