---
name: Erin Sparck's GRE Flashcard Plus MC Test
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://skinnerweb.azurewebsites.net/


dimensions:
  Preparation:
    - type: multipleChoice
    - type: flashcard

  Variation:
    - group: a
    - group: b

steps:
  - task: prepare

  - task: study

  - task: midstudy

  - task: secondStudy

  - task: distract

  - task: exam

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions-gre-{{Preparation.type}}
      next:
        button: Start

  study:
    - type: flashcard
      flashcard set: study-gre
      order: random
      time front: 3 seconds
      time back: 9 seconds

  midstudy:
    - type: text
      content file: midstudy-gre-{{Preparation.type}}
      next:
        button: Go

  secondStudy:
    - show: if {{Preparation.type}} is "flashcard"
      type: flashcard
      flashcard set: study-gre
      order: random
      time front: 3 seconds
      time back: 9 seconds

    - show: if {{Preparation.type}} is "multipleChoice"
      type: test
      style: multipleChoiceSequential
      question set: gre-study-mc-{{Variation.group}}
      order: random
      time: 12 seconds
      show timer: with 5 seconds left
      show answer labels: true
      sequential answer initial delay: 3 seconds
      sequential answer time: 0 seconds

  distract:
    - type: distractor
      exercise: tetris
      time: 5 seconds
      # TODO: 5 minutes
      content: You are now going to play Tetris.

  exam:
    - type: text
      content file: preexam-gre
      next:
        button: Go

    - type: test
      style: multipleChoice
      question set: final-gre
      order: random
      next:
        button: Next

  survey:
    - type: test
      title: Please answer the following.
      question set: survey-gre
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
