---
name: Erin Sparck's variable-encoding-beliefs Experiment
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: random

data collection:
  type: upload to server
  server: http://lowcost-env.p6wx2af6qp.us-east-1.elasticbeanstalk.com/report


dimensions:
  Condition:
    - type: ALL

steps:
  - task: prepare

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

  survey:
    - type: test
      title: Please read the following and answer the questions.
      question set: survey-variable-encoding-beliefs
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the survey. Thank you!
      content file: finish
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
