---
name: Erin Sparck's Sequential vs Simultaneous Presentation Experiment 1
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://skinnerweb.azurewebsites.net/


dimensions:
  Preparation:
    - type: multipleChoice
    - type: multipleChoiceSequential

  Instruction:
    - type: think
    - type: nothink

  Order:
    - passage: [saturn, yellowstone]
    - passage: [yellowstone, saturn]

  Variation:
    - practice: a
      exam: b
    - practice: b
      exam: a

steps:
  - task: prepare

  - task: study
    repeat: across Order.passage
    in between task: midstudy

  - task: distract

  - task: exam
    repeat: across Order.passage

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions-{{Preparation.type}}-{{Instruction.type}}
      next:
        button: Start


  study:
    - type: text
      title: Passage {{_index}}
      content file: passage-{{indexed Order.passage}}
      time: 9 minutes

    - type: countdown
      title: You are about to start the test in...
      time: 3 seconds

    - type: test
      style: {{Preparation.type}}
      question set: {{indexed Order.passage}}-{{Variation.practice}}
      order: random
      time: 30 seconds
      show timer: with 5 seconds left
      show answer labels: true
      show test results: on completion
      sequential answer initial delay: 10 seconds
      sequential answer time: 5 seconds

  midstudy:
    - type: text
      title: You are about to read the next passage.
      content: Click next when ready to begin.
      next:
        button: Next

  distract:
    - type: distractor
      exercise: tetris
      time: 5 minutes
      content: You are now going to play Tetris.

  exam:
    - type: test
      style: cuedRecall
      question set: {{indexed Order.passage}}-{{Variation.exam}}
      order: random
      next:
        button: Next

    - type: test
      style: cuedRecall
      question set: {{indexed Order.passage}}-{{Variation.practice}}
      order: random
      next:
        button: Next

  survey:
    - type: test
      title: Please answer the following.
      question set: survey-{{Preparation.type}}
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
