---
name: Erin Sparck's Testing Effect- Video Versus Text Phase 2
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: email

data collection:
  type: upload to server
  server: http://skinnerweb.azurewebsites.net/


dimensions:
  Dummy:
    - None: nada

steps:
  - task: prepare

  - task: exam

  - task: finish


tasks:
  prepare:
    - type: text
      title: Instructions
      content file: instructions-TEVVTPhase2
      next:
        button: Start

  exam:
    - type: test
      style: freeResponse
      title: Please answer the question
      question set: tevvtPhase2-free-response
      time: 5 minutes
      show next button after time: true
      next:
        button: Next

    - type: test
      style: freeResponse
      title: Please answer the question to the best of your ability
      question set: tevvtPhase2-transfer
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish-lightning-phase2
      error text: An error has occured. Please do <b>NOT</b> close the window. Please contact <a href="mailto:emsparck@ucla.edu">emsparck@ucla.edu</a> for futher instructions.
