---
name: Erin Sparck's Marginal Knowledge Experiment
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://skinnerweb.azurewebsites.net/

dimensions:
  Variation:
    - practice: a
    - practice: b


steps:
  - task: prepare

  - task: initialTest

  - task: distract

  - task: finalExam

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions-marginalKnowledge
      next:
        button: Start

  initialTest:
    - type: test
      style: multipleChoice
      question set: practice-{{Variation.practice}}
      order: random
      next:
        button: Next
      show answer labels: true

  midstudy:
    - show: if {{Preparation.type}} is "studyOnly"
      type: distractor
      exercise: tetris
      time: 250 seconds
      content: You are now going to play Tetris.

    - type: text
      title: You are about to read the next passage.
      content: Click next when ready to begin.
      next:
        button: Next

  distract:
    - type: distractor
      exercise: tetris
      time: {{Preparation.distractionTaskTime}}
      content: You are now going to play Tetris.

  exam:
    - type: test
      style: cuedRecall
      question set: {{indexed Order.passage}}-{{Variation.exam}}
      order: random
      next:
        button: Next

  survey:
    - type: test
      title: Please answer the following.
      question set: survey-{{Preparation.type}}
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
