---
name: Erin Sparck's Confidence Weighted Transfer 2
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://lowcost-env.p6wx2af6qp.us-east-1.elasticbeanstalk.com/report


dimensions:
  Preparation:
    - type: multipleChoice
    - type: triangle

  Order:
    - study: saturn
      secondstudy: yellowstone
    - study: yellowstone
      secondstudy: saturn

  Variation:
    - practice: a
      exam: b
    - practice: b
      exam: a

steps:
  - task: prepare

  - task: passagereading

  - task: midstudy

  - task: practicetests

  - task: distract

  - task: exam

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions-{{Preparation.type}}
      next:
        button: Start

    - show: if {{Preparation.type}} is "triangle"
      type: test
      question set: example
      require correct answer: true
      incorrect answer message: That's not correct. Try again.
      report results: false
      next:
        button: Next

    - show: if {{Preparation.type}} is "triangle"
      type: text
      title: You're ready to begin
      content: If you have any questions, please contact the experimenter before proceeding.
      next:
        button: Begin


  passagereading:
    - type: text
      title: Passage 1
      content file: passage-{{Order.study}}
      time: 9 minutes

    - type: countdown
      title: You are about to read the next passage.
      time: 3 seconds

    - type: text
      title: Passage 2
      content file: passage-{{Order.secondstudy}}
      time: 9 minutes

  midstudy:
    - type: text
      title: You are now going to answer some questions.
      content: Click next when ready to begin.
      next:
        button: Next

  practicetests:
    - type: test
      style: {{Preparation.type}}
      question set: {{Order.study}}-{{Variation.practice}}
      order: random
      time: 25 seconds
      show timer: with 10 seconds left
      show answer labels: true
      show test results: on completion

    - type: text
      title: You are now going to answer some more questions.
      content: Click next when ready to begin.
      next:
        button: Next

    - type: test
      style: multipleChoice
      question set: {{Order.secondstudy}}-{{Variation.practice}}
      order: random
      time: 25 seconds
      show timer: with 10 seconds left
      show answer labels: true
      show test results: on completion

  distract:
    - type: distractor
      exercise: tetris
      time: 5 minutes
      content: You are now going to play Tetris.

  exam:
    - type: test
      style: cuedRecall
      question set: {{Order.secondstudy}}-{{Variation.exam}}
      order: random
      next:
        button: Next

  survey:
    - type: test
      title: Please answer the following.
      question set: survey-cwtransfer-two
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
