---
name: Erin Sparck's Triangle Experiment
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

reporting:
  type: download


dimensions:
  Preparation:
    - type: multipleChoice
    - type: triangle
    - type: studyOnly

  Order:
    - passage: [saturn, yellowstone]
    - passage: [yellowstone, saturn]

  Variation:
    - practice: a
      exam: b
    - practice: b
      exam: a


steps:
  - task: prepare

  - task: study
    repeat: across Order.passage

  - task: distract

  - task: exam
    repeat: across Order.passage

  - task: finish


tasks:
  prepare:
    - type: text
      title: Instructions
      content file: instructions-{{Preparation.type}}
      next:
        button: Start

    - show: if {{Preparation.type}} is "triangle"
      type: test
      style: triangle
      question set: example
      next:
        button: I understand it!

  study:
    - type: text
      title: Passage {{_index}}
      content file: passage-{{indexed Order.passage}}
      next:
        button: Continue

    - type: countdown
      title: You are about to start the test in...
      time: 3 seconds

    - type: test
      style: {{Preparation.type}}
      question set: {{indexed Order.passage}}-{{Variation.practice}}
      # TODO: This should be:
      # time: 30 seconds
      next:
        button: Next
      feedback: final score
      show answer labels: true

  distract:
    - type: distractor
      exercise: tetris
      time: 4 minutes
      # TODO: Can we use title? this content is not centered!
      content: You are now going to play Tetris.
      # TODO: Remove
      next:
        button: Go!

  exam:
    - type: test
      style: cuedRecall
      question set: {{indexed Order.passage}}-{{Variation.exam}}
      next:
        button: Next

  finish:
    - type: text
      title: You have now completed the experiment on human memory and learning.
      content file: finish
      next:
        button: submit
