---
name: Erin Sparck's Triangle Experiment
authors: [Erin Sparck, Robert Bjork, Elizabeth Bjork]


login: 
  type: basic


dimensions:
  Preparation:
    - name: multipleChoice
      questionType: multipleChoice

    - name: triangle
      questionType: triangle

  Order:
    - passageId: [1, 2]
    - passageId: [2, 1]


steps:
  - task: prepare

  - task: study
    repeat: across {{Order.passageId}}

  - task: distract

  - task: exam


tasks:
  prepare:
    - type: text
      title: Instructions
      contentFile: instructions-{{Preparation.name}}
      nextButton: Start

    - show: if {{Preparation.name}} is "triangle"
      type: test
      style: triangle
      questionSet: example
      nextButton: I understand it!

  study:
    - type: text
      title: Passage {{%%index}}
      contentFile: passage{{%Order.passageId}}
      nextButton: Continue

    - type: countdown
      title: You are about to start the test in...
      time: 2 seconds

    - type: test
      style: >{{Preparation.questionType}}
      questionSet: passage{{%Order.passageId}}-a
      time: 2 seconds

  distract:
    - type: distractor
      exercise: tetris
      time: 2 seconds
      content: You are now going to play Tetris for 9 minutes.

  exam:
    - type: test
      style: cuedRecall
      questionSet: passage1-a
      nextButton: Next
