---
name: Erin Sparck's Triangle Experiment
authors: [Erin Sparck, Robert Bjork, Elizabeth Bjork]

login: 
  type: basic


dimensions:
  Preparation:
    - name: multipleChoice
      questionType: multipleChoice
    - name: triangle
      questionType: triangle

  Order:
    - passageId: [1, 2]
    - passageId: [2, 1]

  PracticeList:
    - name: A then B
      practice: A
      exam: B
    - name: B then A
      practice: B
      exam: A


steps:
  - task: prepare

  - task: study
    repeat: across {{Order.passageId}}

  - task: distract

  - task: exam
    repeat: across {{Order.passageId}}


tasks:
  prepare:
    - type: text
      title: Instructions
      content file: instructions-{{Preparation.name}}
      next button: Start

    - show: if {{Preparation.name}} is "triangle"
      type: test
      style: triangle
      question set: example
      next button: I understand it!

  study:
    - type: text
      title: Passage {{%%index}}
      content file: passage{{%Order.passageId}}
      next button: Continue

    - type: countdown
      title: You are about to start the test in...
      time: 2 seconds

    - type: test
      style: {{Preparation.questionType}}
      question set: passage{{%Order.passageId}}-{{PracticeList.practice}}
      time: 2 seconds

  distract:
    - type: distractor
      exercise: tetris
      time: 2 seconds
      content: You are now going to play Tetris for 9 minutes.

  exam:
    - type: test
      style: cuedRecall
      questions set: passage{{%Order.passageId}}-{{PracticeList.exam}}
      next button: Next
