---
name: Erin Sparck's pretest-mc-mc+confjudgment-cw-studyonly Experiment
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://skinnerweb.azurewebsites.net/


dimensions:
  Preparation:
    - type: multipleChoice
      distractionTaskTime: 5 minutes
    - type: multipleChoiceConfidence
      distractionTaskTime: 5 minutes
    - type: triangle
      distractionTaskTime: 5 minutes
    - type: studyOnly
      distractionTaskTime: 550 seconds


  Order:
    - passage: [saturn, yellowstone]
    - passage: [yellowstone, saturn]

  Variation:
    - practice: a
      exam: b
    - practice: b
      exam: a

steps:
  - task: prepare

  - task: study
    repeat: across Order.passage
    in between task: midstudy

  - task: distract

  - task: exam
    repeat: across Order.passage

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions-{{Preparation.type}}
      next:
        button: Start


  study:
    - show: unless {{Preparation.type}} is "studyOnly"
      type: test
      style: {{Preparation.type}}
      question set: {{indexed Order.passage}}-{{Variation.practice}}
      order: random
      time: 25 seconds
      show timer: with 10 seconds left
      show answer labels: true
      show test results: on completion

    - show: unless {{Preparation.type}} is "studyOnly"
      type: countdown
      title: You are about to read the passage in...
      time: 3 seconds

    - type: text
      title: Passage {{_index}}
      content file: passage-{{indexed Order.passage}}
      time: 9 minutes


  midstudy:
    - show: if {{Preparation.type}} is "studyOnly"
      type: distractor
      exercise: tetris
      time: 250 seconds
      content: You are now going to play Tetris.

    - type: text
      title: You are about to move onto the next section.
      content: Click next when ready to begin.
      next:
        button: Next

  distract:
    - type: distractor
      exercise: tetris
      time: {{Preparation.distractionTaskTime}}
      content: You are now going to play Tetris.

  exam:
    - type: test
      style: cuedRecall
      question set: {{indexed Order.passage}}-{{Variation.exam}}
      order: random
      next:
        button: Next

  survey:
    - type: test
      title: Please answer the following.
      question set: survey-{{Preparation.type}}
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
