---
name: Erin Sparck's Triangle Experiment

pages:
  - type: text
    title: Instructions
    contentFile: instructions
    nextButton: Start

  - type: text
    title: Passage 1
    contentFile: passage1
    nextButton: Continue

  - type: test
    style: multipleChoice
    questionSet: multipleChoiceQuestions-1
    time: 2 seconds

  - type: test
    style: cuedRecall
    questionSet: multipleChoiceQuestions-1
    time: 5 seconds
    nextButton: Next page

  - type: test
    style: triangle
    pointsPerEdge: 2
    questionSet: multipleChoiceQuestions-1
    time: 2 seconds
    order: random

  - type: text
    title: Passage 2
    contentFile: passage2
    nextButton: Next page

  - type: distractor
    exercise: tetris
    time: 9 minutes

