---
name: Erin Sparck's Triangle Experiment
authors: [Erin Sparck, Robert Bjork, Elizabeth Bjork]

login:
  type: basic


dimensions:
  Preparation:
    - questionType: multipleChoice
    - questionType: triangle

  Order:
    - passageId: [1, 2]
    - passageId: [2, 1]

  PracticeList:
      practice: A
      exam: B
      practice: B
      exam: A


steps:
  - task: prepare

  - task: study
    repeat: across Order.passageId

  - task: distract

  - task: exam
    repeat: across Order.passageId

  - task: finish

tasks:
  prepare:
    - type: text
      title: Instructions
      content file: instructions-{{Preparation.questionType}}
      next:
        button: Start
        keys: [space, right]

    - show: if {{Preparation.questionType}} is "triangle"
      type: test
      style: triangle
      question set: example
      next:
        button: I understand it!

  study:
    - type: text
      title: Passage {{%%index}}
      content file: passage{{%Order.passageId}}
      next:
        button: Continue

    - type: countdown
      title: You are about to start the test in...
      time: 3 seconds

    - type: test
      style: {{Preparation.questionType}}
      question set: passage{{%Order.passageId}}-a
      # time: 2 seconds
      next:
        button: Next
      feedback: final score
      showAnswerLabels: true

  distract:
    - type: distractor
      exercise: tetris
      time: 4 minutes
      content: You are now going to play Tetris for 4 minutes.
      next:
        button: Go!

  exam:
    - type: test
      style: cuedRecall
      question set: passage{{%Order.passageId}}-a
      next:
        button: Next

  finish:
    - type: text
      title: Experiment completed
      content: Submit your results.
      next:
        button: submit
