---
name: Erin Sparck's Triangle Experiment
login: basic

pages:
  - type: text
    title: Instructions
    contentFile:
    contentFile: instructions-{{Practice Type}}
    time: 3 seconds
    nextButton: Start

  # - type: test
  #   style: triangle
  #   questionSet: example
  #   nextButton: I understand it!

  # - task: study

  - type: text
    title: Passage 1
    contentFile: passage1
    nextButton: Continue

  - type: countdown
    title: You are about to start the test in...
    time: 5 seconds

  - type: test
    style: multipleChoice
    questionSet: passage1-a
    time: 5 seconds

  - type: test
    style: cuedRecall
    questionSet: passage1-a
    nextButton: Next

  - type: test
    style: triangle
    questionSet: passage1-a
    time: 20 seconds
    order: random

  - type: text
    title: Passage 2
    contentFile: passage2
    time: 3 seconds
    nextButton: Next

  - type: countdown
    title: You are about to start the test in...
    time: 5 seconds

  - type: distractor
    exercise: tetris
    time: 9 minutes


tasks:
  study:
    - type: text
      title: Passage 1
      contentFile: passage
      nextButton: Continue

    - type: countdown
      title: You are about to start the test in...
      time: 5 seconds

    - type: test
      style: multipleChoice
      questionSet: passage1-a
      time: 5 seconds
