---
name: Erin Sparck's Marginal Knowledge Experiment
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://skinnerweb.azurewebsites.net/


steps:
  - task: prepare

  - task: initialTest

  - task: finalExam

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      question set: demographics
      inline: true
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions-marginalKnowledge
      next:
        button: Start

  initialTest:
    - type: test
      style: multipleChoice
      question set: marginalKnowledge
      select: 1 randomly from [T1, T2, T3, T4, T5, T6, T7]
      order: random
      time: 12 seconds
      show timer: with 5 seconds left
      show answer labels: true

  finalExam:
    - type: test
      style: cuedRecall
      question set: marginalKnowledge
      select: 2 randomly from [T1, T2, T3, T4, T5, T6, T7], 14 randomly from [general]
      order: random
      require answer: true
      next:
        button: Next

  survey:
    - type: test
      title: Please answer the following.
      question set: survey
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish
