---
name: Erin Sparck's CW Vocabulary Experiment Part 1
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://lowcost-env.p6wx2af6qp.us-east-1.elasticbeanstalk.com/report


dimensions:
  Preparation:
    - type: multipleChoice
    - type: triangle
    - type: cuedRecall
    - type: studyOnly

  Group:
    - wordset: 1
    - wordset: 2
    - wordset: 3


steps:
  - task: prepare

  - task: study

  - task: study

  - task: distract

  - task: exam

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

    - show: if {{Preparation.type}} is "triangle"
      type: text
      title: Instructions
      content file: tutorial-triangle
      next:
        button: Next

    - show: if {{Preparation.type}} is "triangle"
      type: test
      question set: example
      require correct answer: true
      incorrect answer message: That's not correct. Try again.
      report results: false
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions
      next:
        button: Start

  study:
    - type: wordpair
      wordpair sets:
        - wordset-1
        - wordset-2
        - wordset-3
      aKey: word
      bKey: definition
      order: random
      time: 5 seconds

  distract:
    - type: distractor
      exercise: tetris
      time: 5 minutes
      content: You will now play Tetris for 5 minutes.

  exam:
    - type: text
      title: Test Instructions
      content file: exam-instructions-{{Preparation.type}}
      next:
        button: Start

    - show: unless {{Preparation.type}} is "studyOnly"
      type: test
      style: {{Preparation.type}}
      question set: exam-words-{{Group.wordset}}
      order: random
      time: 25 seconds
      show timer: with 10 seconds left
      show answer labels: true

    - show: if {{Preparation.type}} is "studyOnly"
      type: wordpair
      wordpair set: wordset-{{Group.wordset}}
      aKey: word
      bKey: definition
      order: random
      time: 25 seconds

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
