---
name: Erin Sparck's Triangle Experiment
authors: [Erin Sparck, Robert Bjork, Elizabeth Bjork]

login: 
  type: basic


steps:
  - task: prepare

  - task: study
    repeat-with: passages

  - task: distract

  - task: exam


tasks:
  prepare:
    - type: text
      title: Instructions
      contentFile: instructions-{{Preparation.name}}
      time: 3 seconds
      nextButton: Start

    - type: test
      style: triangle
      questionSet: example
      nextButton: I understand it!

  study:
    - type: text
      title: Passage {{NUM}}
      contentFile: passage{{NUM}}
      nextButton: Continue

    - type: countdown
      title: You are about to start the test in...
      time: 5 seconds

    - type: test
      style: >{{Preparation.questionType}}
      questionSet: passage{{NUM}}-a
      time: 5 seconds

  distract:
    - type: distractor
      exercise: tetris
      time: 9 minutes
      content: You are now going to play Tetris for 9 minutes.

  exam:
    - type: test
      style: cuedRecall
      questionSet: passage1-a
      nextButton: Next
