---
name: Erin Sparck's variable-encoding-beliefs-choose-trial Experiment
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: random

data collection:
  type: upload to server
  server: http://lowcost-env.p6wx2af6qp.us-east-1.elasticbeanstalk.com/report


dimensions:
  Condition:
    - type: ALL

steps:
  - task: prepare

  - task: study # 1

  - task: prompt

  - task: testA
    context: 1

  - task: restudy # 2

  - task: testA
    context: 2

  - task: restudy # 3

  - task: reprompt

  - task: testB
    context: 3

  - task: restudy # 4

  - task: testB
    context: 4

  - task: distract

  - task: exam

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions
      next:
        button: Start

  study:
    - type: wordpair
      wordpair set: wordset
      aKey: lithuanian
      bKey: english
      order: random
      time: 5 seconds

  restudy:
    - type: text
      content: Please study the words again.
      next:
        button: Next

    - type: wordpair
      wordpair set: wordset
      aKey: lithuanian
      bKey: english
      order: random
      time: 5 seconds

  prompt:
    - type: test
      content: Now you will be given a practice test on the pairs as if you were using flashcards. Would you like to be given the Lithuanian word and asked to retrieve the English word?  Or given the English word and asked to retrieve the Lithuanian words?
      style: multipleChoice
      question set: first-prompt
      next:
        button: Next

  testA:
    - type: text
      content: Type the correct answer in the box provided.  Don't worry about exact spelling, but try your best and do not leave anything blank.  You will be given 8 seconds to type an answer in before automatically being moved on to the next word.
      next:
        button: Begin

    - show: if "{{reported "prompt-test-multipleChoice-first-prompt" "1" "answer"}}" is "Given English; Retrieve Lithuanian"
      type: test
      style: cuedRecall
      order: random
      time: 8 seconds
      dynamic questions:
        wordpair set: wordset
        questionKey: english
        answerKey: lithuanian

    - show: if "{{reported "prompt-test-multipleChoice-first-prompt" "1" "answer"}}" is "Given Lithuanian; Retrieve English"
      type: test
      style: cuedRecall
      order: random
      time: 8 seconds
      dynamic questions:
        wordpair set: wordset
        questionKey: lithuanian
        answerKey: english

  reprompt:
    - type: test
      content: Now you will be given another practice test on the pairs using flashcards.  Would you like to be given the Lithuanian word and asked to retrieve the English word?  Or given the English word and asked to retrieve the Lithuanian words?
      style: multipleChoice
      question set: second-prompt
      next:
        button: Next

  testB:
    - type: text
      content: Type the correct answer in the box provided.  Don't worry about exact spelling, but try your best and do not leave anything blank.  You will be given 8 seconds to type an answer in before automatically being moved on to the next word.
      next:
        button: Begin

    - show: if "{{reported "reprompt-test-multipleChoice-second-prompt" "1" "answer"}}" is "Given English; Retrieve Lithuanian"
      type: test
      style: cuedRecall
      order: random
      time: 8 seconds
      dynamic questions:
        wordpair set: wordset
        questionKey: english
        answerKey: lithuanian

    - show: if "{{reported "reprompt-test-multipleChoice-second-prompt" "1" "answer"}}" is "Given Lithuanian; Retrieve English"
      type: test
      style: cuedRecall
      order: random
      time: 8 seconds
      dynamic questions:
        wordpair set: wordset
        questionKey: lithuanian
        answerKey: english


  distract:
    - type: distractor
      exercise: tetris
      time: 10 minutes
      content: You will now play Tetris.

  exam:
    - type: text
      content: You will be tested on the words one final time. Type the correct answer in the box provided. Don't worry about exact spelling, but try your best and do not leave anything blank.  You will be given 12 seconds to type an answer in before automatically being moved on to the next word.
      next:
        button: Begin

    - type: test
      style: cuedRecall
      order: random
      time: 12 seconds
      dynamic questions:
        wordpair set: wordset
        randomKeys:
          - english
          - lithuanian

  survey:
    - type: test
      title: Please answer the following.
      question set: survey
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
