---
name: Erin Sparck's Testing Effect- Video Versus Text
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://skinnerweb.azurewebsites.net/


dimensions:
  Study:
    - type: video
    - type: text

  FollowUp:
    - type: repeat
    - type: practiceTest

steps:
  - task: prepare

  - task: study

  - task: midStudy

  - task: followUp

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: test
      title: Participation
      content file: participation
      question set: demographics
      inline: true
      next:
        button: Next

    - type: text
      title: Instructions
      content file: instructions-{{Study.type}}
      next:
        button: Start

  study:
    - type: text
      title: How lightning is formed
      content file: study-{{Study.type}}
      time: 192 seconds
      show next button after time: true
      next:
        button: Next

  midStudy:
    - type: text
      content file: midStudy-{{FollowUp.type}}
      next:
        button: Next

  followUp:
    - show: if {{FollowUp.type}} is "repeat"
      type: text
      title: How lightning is formed
      content file: study-{{Study.type}}
      time: 192 seconds
      show next button after time: true
      next:
        button: Next

    - show: if {{FollowUp.type}} is "practiceTest"
      type: test
      style: multipleChoice
      question set: lightningPractice
      time: 24 seconds
      show timer: with 10 seconds left
      show answer labels: true

  survey:
    - type: test
      title: Please answer the following.
      question set: survey-lightning
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: finish-lightning
      error text: Please do <b>NOT</b> close the window. Please go get your experimenter.
