---
name: Erin Sparck's CW Vocabulary Experiment Part 2
authors: [Erin M. Sparck, Robert A. Bjork, Elizabeth L. Bjork]

login:
  type: basic

data collection:
  type: upload to server
  server: http://lowcost-env.p6wx2af6qp.us-east-1.elasticbeanstalk.com/report


dimensions:
  Preparation:
    - type: multipleChoice
    # - type: triangle
    # - type: cuedRecall
    # - type: studyOnly

  Group:
    - wordset: 1
      other-wordset-a: 2
      other-wordset-b: 3
    - wordset: 2
      other-wordset-a: 1
      other-wordset-b: 3
    - wordset: 3
      other-wordset-a: 1
      other-wordset-b: 2


steps:
  - task: prepare

  - task: exam

  - task: survey

  - task: finish


tasks:
  prepare:
    - type: text
      title: Instructions
      content file: part2-instructions
      next:
        button: Start

  exam:
    - type: test
      style: cuedRecall
      question set: exam-words-{{Group.other-wordset-a}}
      order: random
      next:
        button: Next

    - type: test
      style: cuedRecall
      question set: exam-words-{{Group.other-wordset-b}}
      order: random
      next:
        button: Next

    - type: test
      style: cuedRecall
      question set: exam-words-{{Group.wordset}}
      order: random
      next:
        button: Next

  survey:
    - type: test
      title: Please answer the following.
      question set: survey-{{Preparation.type}}
      inline: true
      next:
        button: Next

  finish:
    - type: finish
      title: You have now completed the experiment.
      content file: part2-finish
      error text: Please do <b>NOT</b> close the window. Please contact emsparck@ucla.edu.
