---

study-gre:
  - word: Pith
    definition: the core or essence
  - word: Crotchet
    definition: a perverse or unfounded belief or notion
  - word: Disportment
    definition: an amusement or diversion
  # - word: Frisson
  #   definition: a sudden strong feeling of excitement or fear
  # - word: Scintilla
  #   definition: a tiny trace of a specified quality or feeling
  # - word: Proprinquinty
  #   definition: the state of being close to someone or something
  # - word: Morass
  #   definition: a complicated or confused situation
  # - word: Patois
  #   definition: the informal speech used by a particular social group
  # - word: Erudition
  #   definition: the quality of having or showing great knowledge
  # - word: Languor
  #   definition: the state or feeling, often pleasant, of tiredness or inertia
  # - word: Mélange
  #   definition: a mixture or medley
  # - word: Indolence
  #   definition: the avoidance of activity or exertion
  # - word: Detritus
  #   definition: waste or debris
  # - word: Apogee
  #   definition: the climax or culmination
  # - word: Chagrin
  #   definition: distress or embarrassment at having failure or humiliation
  # - word: Chicanery
  #   definition: the use of trickery to achieve some purpose
  # - word: Periphrasis
  #   definition: the use of indirect speech or writing
  # - word: Truculence
  #   definition: the disposition to use violence
  # - word: Temerity
  #   definition: excessive confidence or boldness
  # - word: Exponent
  #   definition: a champion or advocate
