---

wordset:
  - lithuanian: kirvis
    english: axe
  - lithuanian: vonia
    english: bath
  - lithuanian: dazai
    english: paint
  - lithuanian: smuikas
    english: violin
  - lithuanian: gatve
    english: street
  - lithuanian: varpas
    english: bell
  - lithuanian: muilas
    english: soap
  - lithuanian: krantas
    english: shore
  - lithuanian: masina
    english: car
  - lithuanian: kreida
    english: chalk
  - lithuanian: arbata
    english: tea
  - lithuanian: tvora
    english: fence
  - lithuanian: sakute
    english: fork
  - lithuanian: plaukas
    english: hair
  - lithuanian: adata
    english: needle
  - lithuanian: sokis
    english: dance
  - lithuanian: sketis
    english: umbrella
  - lithuanian: vinis
    english: nail
  - lithuanian: pienas
    english: milk
  - lithuanian: auksas
    english: gold
  - lithuanian: kede
    english: chair
  - lithuanian: urvas
    english: cave
  - lithuanian: kelnes
    english: pants
  - lithuanian: koja
    english: leg
  - lithuanian: dumai
    english: smoke
  - lithuanian: duona
    english: bread
  - lithuanian: zole
    english: grass
  - lithuanian: rusys
    english: basement
  - lithuanian: ugnis
    english: fire
  - lithuanian: nafta
    english: oil
  - lithuanian: akis
    english: eye
  - lithuanian: langas
    english: window
