wordset-1:
  - word: Abnegate
    definition: refuse, reject
  - word: Compunction
    definition: feeling of guilt, regret
  - word: Expiate
    definition: do something as a way of showing you are sorry
  - word: Inchoate
    definition: only partly in existence, not perfectly formed
  - word: Obsequious
    definition: servile, obedient, compliant
  - word: Pernicious
    definition: highly damaging
  - word: Staid
    definition: serious, boring, old-fashioned
  - word: Tenebrous
    definition: hard to understand, obscure
  - word: Visceral
    definition: obtained through intuition rather than through reasoning
  - word: Maculate
    definition: spotted; blotched
  - word: Querulous
    definition: complaining 
  - word: Recumbent
    definition: reclining

wordset-2:
  - word: Aver
    definition: assert or affirm strongly
  - word: Calumny
    definition: untrue statement made to damage someone's reputation
  - word: Expurgate
    definition: change a written text by removing offensive parts
  - word: Inveterate
    definition: always happening, habitual, ingrained
  - word: Obstreperous
    definition: noisy and defiant
  - word: Punctilious
    definition: precise about doing things in an accurate way
  - word: Sedulous
    definition: diligent, devoted
  - word: Taciturn
    definition: reserved in speech, tending to be silent
  - word: Venal
    definition: corruptible, bribable
  - word: Maladroit
    definition: clumsy, not skillful
  - word: Quiescent
    definition: temporarily inactive
  - word: Redolent
    definition: odorous, fragrant

wordset-3:
  - word: Allay
    definition: put fears to rest, calm, mitigate 
  - word: Conciliation
    definition: act of placating, reconciling, winning over
  - word: Excoriate
    definition: criticize harshly
  - word: Irascible
    definition: easily angered
  - word: Officious
    definition: intrusive and offering services even though they are unwanted, meddlesome
  - word: Perspicacious
    definition: having keen insight and understanding
  - word: Scurrilous
    definition: obscene, vulgar
  - word: Trifling
    definition: trivial, insignificant
  - word: Veracious
    definition: honest, unwilling to tell lies
  - word: Maudlin
    definition: effusively sentimental
  - word: Quixotic
    definition: idealistic but impractical
  - word: Refulgent
    definition: brightly shining; gleaming
